export enum CommandCode {
  DISTRIBUTE_ERC20_AMOUNTS = 3,
  DISTRIBUTE_ERC20_SHARES = 4,
  WRAP_AND_DISTRIBUTE_ERC20_AMOUNTS = 5,
  UNWRAP_NATIVE = 6,
  SWAP_UNISWAP_V2 = 10,
  SWAP_ZENLINK_STABLE_POOL = 20,
}
